# Generated by Django 6.0 on 2025-12-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.IntegerField(blank=True, choices=[(0, 'Admin'), (1, 'Applicant'), (2, 'Employer')], null=True),
        ),
    ]
